# Modulo numpy
El modulo numpy es parte del paquete de Python scipy, que permite agregar al lenguaje de programación capacidades de calculo científico, incluyendo un objeto nuevo: el arreglo.

In [5]:
#Numpy es el acronimo de 'Numeric Python'. Es una extension de codigo abierto de
#Python que permite ejecutar rutinas matemáticas avanzadas precompiladas.
                 
#Las ventajas de Python con Numpy:
#    - Computación orientada al arreglo
#    - Implementación eficiente de arreglos multidimensionales
#    - Diseñada para la computación científica

In [2]:
import numpy as np

## Arreglos unidimensionales (vectores)
Se define un arreglo simple con una lista

In [8]:
# El arreglo a a partir de una lista
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9,])
# Se verifica que no es una lista sino un arreglo
print(type(a))
# Se imprime el contenido del arreglo
print("Array a = ",a)

<class 'numpy.ndarray'>
Array a =  [0 1 2 3 4 5 6 7 8 9]


Se puede acceder a los elementos de un arreglo como si fuera una lista *[inicio:fin:paso]*  *por defecto[0:end-1:1]*

In [9]:
print("Primer elemento:", a[0])
print("Ultimo elemento:", a[-1])
print("Tres primeros elementos:", a[:3])
print("Dos ultimos elementos:", a[-2:])
print("Elementos de indice par:", a[1:-1:2])
print("Del elemento 2do al 4to:", a[1:4])

Primer elemento: 0
Ultimo elemento: 9
Tres primeros elementos: [0 1 2]
Dos ultimos elementos: [8 9]
Elementos de indice par: [1 3 5 7]
Del elemento 2do al 4to: [1 2 3]


Se pueden examinar los elementos de un arreglo

In [12]:
a = np.array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],[1,2,3,5,6,7,8,9,10]])
print(a)
print("Tamaño del arreglo:", a.size)
print("Dimensiones del arreglo:", a.shape)
print("Tipo de datos:", a.dtype)
print("Cantidad de memoria por dato (bytes):", a.itemsize)
print("Memoria total (bytes):", a.size * a.itemsize)

[list([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]) list([1, 2, 3, 5, 6, 7, 8, 9, 10])]
Tamaño del arreglo: 2
Dimensiones del arreglo: (2,)
Tipo de datos: object
Cantidad de memoria por dato (bytes): 8
Memoria total (bytes): 16


Otra forma de crear una lista es utilizando el método rango de numpy (np.arange)

In [3]:
a = np.arange(10,dtype=float)
print("np.arrange(10) =", a)
a = np.arange(1,10)
print("np.arrange(1,10) =", a)
a = np.arange(1,10,2)
print("np.arrange(1,10,2) =", a)
a = np.arange(10, 0, -1)
print("np.arrange(10,0,-1) =", a)
a = np.arange(1, 10, 0.5)
print("np.arrange(1,10,0.5) =", a)

np.arrange(10) = [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
np.arrange(1,10) = [1 2 3 4 5 6 7 8 9]
np.arrange(1,10,2) = [1 3 5 7 9]
np.arrange(10,0,-1) = [10  9  8  7  6  5  4  3  2  1]
np.arrange(1,10,0.5) = [1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5 9.  9.5]


Por defecto, los datos de un array dependeran de los argumentos del método arange. En el ejemplo anterior los datos 1. 1.5 2. hacen referencia a 1.0 1.5 2.0, es decir, son float. Para especificar que se requiere que un valor sea de un tipo especifico se puede usar el atributo dtype

In [13]:
print(np.arange(1,10, 2, dtype=np.float64))
print(np.arange(1,10, 2, dtype=np.int64))


[1. 3. 5. 7. 9.]
[1 3 5 7 9]


A veces es util generar N datos entre dos valores
Esto se puede realizar con la método np.linspace(ini, fin, num_elementos)

In [15]:
a = np.linspace(0, 10, 5)
print("np.linspace(0, 10, 5) =", a)
a = np.linspace(10, 0, 5)
print("np.linspace(10, 0, 5) =", a)

np.linspace(0, 10, 5) = [ 0.   2.5  5.   7.5 10. ]
np.linspace(10, 0, 5) = [10.   7.5  5.   2.5  0. ]


Si no se especifica el numero de elementos que se requieren en np.linspace, se generan 50 elementos:

In [20]:
a = np.linspace(0, 10)
print("np.linspace(0, 10) =", a)
print()
print("Numero de elementos:", np.size(a))

np.linspace(0, 10) = [ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ]

Numero de elementos: 50


Un arreglo tiene ciertos atributos:

In [19]:
print("a = ", a)
print("Numero de elementos:", np.size(a))   
print("Dimensiones:",np.ndim(a))
print("Forma del arreglo:", np.shape(a))

a =  [ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ]
Numero de elementos: 50
Dimensiones: 1
Forma del arreglo: (50,)


Se observa que el método np.linspace() incluye en el arreglo generado el número final, lo que lo distinge de np.arange(). Se puede ajustar esto de forma que no incluya el valor final:

In [31]:
a = np.linspace(0, 10,endpoint=False)
print(a)
print(np.size(a))

[0.  0.2 0.4 0.6 0.8 1.  1.2 1.4 1.6 1.8 2.  2.2 2.4 2.6 2.8 3.  3.2 3.4
 3.6 3.8 4.  4.2 4.4 4.6 4.8 5.  5.2 5.4 5.6 5.8 6.  6.2 6.4 6.6 6.8 7.
 7.2 7.4 7.6 7.8 8.  8.2 8.4 8.6 8.8 9.  9.2 9.4 9.6 9.8]
50


Por que son importantes los arreglos? Por que se puede hacer con ellos operaciones de elemento-a-elemento

In [21]:
lista = range(11)
arreglo = np.arange(11)

'''
for numero in lista
    print(numero**2)
'''

print(list(map(lambda x: x**2, lista)))
print(arreglo**2)

# LAS FUNCIONES MAGICAS SON FUNCIONES QUE SOLO FUNCIONAN EN JUPYTER!!!!
# Utilicemos una "funcion magica" de Python para calcular las diferencias de tiempo de ejecución
# en un cálculo mas demandante
lista = range(10000)
%timeit [i**2 for i in lista]

arreglo = np.array(1000)
%timeit arreglo**2

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81, 100]
[  0   1   4   9  16  25  36  49  64  81 100]
3.8 ms ± 227 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
721 ns ± 29.1 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


## Arreglos bidimensionales (matrices)
Se pueden crear arreglos bidimensionales

In [22]:
matriz = np.array([[1, 2, 3], [4, 5, 6]])
print(matriz)
print("Numero de elementos (mal):", len(matriz))   # Esto esta mal!!!
print("Numero de elementos:", matriz.size)
print("Dimensiones:",np.ndim(matriz))
print("Forma del arreglo:", matriz.shape)

[[1 2 3]
 [4 5 6]]
Numero de elementos (mal): 2
Numero de elementos: 6
Dimensiones: 2
Forma del arreglo: (2, 3)


¿Se pueden crear arreglos n-dimensionales? Si...

In [24]:
cubo = np.array([[[1], [2]], [[3], [4]]])
print(cubo)
print("Numero de elementos:", cubo.size)
print("Dimensiones:",np.ndim(cubo))
print("Forma del arreglo:", cubo.shape)

[[[1]
  [2]]

 [[3]
  [4]]]
Numero de elementos: 4
Dimensiones: 3
Forma del arreglo: (2, 2, 1)


Existen arreglos especiales que son de uso práctico en Algebra Lineal, por ejemplo:

In [25]:
# Arreglo de 1s
a = np.ones((3, 3))
print("np.ones((3, 3)) =")
print(a)
print()
# Arreglo de 0s
a = np.zeros((3, 3))
print("np.zeros((3, 3)) =")
print(a)
print()
# Arreglo Identidad
a = np.eye(5)
print("np.eye(5)=")
print(a)
print()
# Arreglo con una diagonal definida
a = np.diag(([1, 2, 3, 4, 5]))
print("np.diag([1, 2, 3, 4, 5]) =")
print(a)
print()

np.ones((3, 3)) =
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

np.zeros((3, 3)) =
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

np.eye(5)=
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

np.diag([1, 2, 3, 4, 5]) =
[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]



Revisemos con mas detalle el tema de la seleccion de elementos respecto a sus indices (slicing) ya que en una matriz se tienen dos dimensiones

In [26]:
mat = np.arange(36).reshape((6, 6))    #np.reshape(array, (m, n)) -> array(m, n)
print("mat=\n",mat); print()
print("mat[0,0] =", mat[0,0]); print()
print("mat[2,2] =", mat[2,2]); print()
print("mat[-1,-1] =", mat[-1,-1]); print()
print("mat[:,1] =", mat[:,1]); print()
print("mat[2,:] =", mat[2,:]); print()
print("mat[:,1:2] =\n", mat[:,1:2]); print()
print("mat[:,1:3] =\n", mat[:,1:3]); print()

mat=
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]

mat[0,0] = 0

mat[2,2] = 14

mat[-1,-1] = 35

mat[:,1] = [ 1  7 13 19 25 31]

mat[2,:] = [12 13 14 15 16 17]

mat[:,1:2] =
 [[ 1]
 [ 7]
 [13]
 [19]
 [25]
 [31]]

mat[:,1:3] =
 [[ 1  2]
 [ 7  8]
 [13 14]
 [19 20]
 [25 26]
 [31 32]]



Utilizando slicing se pueden modificar los elementos de un arreglo

In [27]:
mat = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
print(mat,"\n")
# Se asigna 10 al elemento elemento en [0,0]
mat[0, 0] = 10
print(mat,"\n")
# Se asigna 0 a toda la segunda columna
mat[:, 1] = 0
print(mat)

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[[10  2  3]
 [ 4  5  6]
 [ 7  8  9]] 

[[10  0  3]
 [ 4  0  6]
 [ 7  0  9]]


## Numeros aleatorios en numpy
numpy incluye un generador de numeros aleatorios que retorna arreglos

In [28]:
a = np.random.rand(4)     # Retorna 4 valores uniformes [0.0 - 1.0>
print(a)
a = np.random.randn(4)    # Distribucion normal (gaussiana)
print(a)
a = np.random.randint(0, 10, 5)  # Retorna 5 valores enteros ente [0 - 9]
print(a)
a = np.random.uniform(0, 10, 5)  # Retorna 5 valores reales entre [0.0 - 9.9]
print(a)
a = np.random.random((1, 2))    # Retorna un arreglo de m,n con valores reales entre [0.0 - 1.0>
print(a)
#Formula para [a-b> : (b - a) * np.random.random(m,n) + a

[0.06595677 0.61853258 0.51410825 0.01827962]
[ 0.97176133 -0.50081618 -0.7435887   1.52578224]
[0 6 9 0 9]
[3.21389389 0.12939589 9.78525277 9.44831936 3.23972328]
[[0.23954119 0.11168622]]


## Operaciones matemáticas en numpy
numpy incluye muchas de las funciones matematicas disponibles en math, 
pero para ser aplicadas directamente sobre un arreglo

In [29]:
ang = np.linspace(-2*np.pi, 2*np.pi, 20)
y = np.sin(ang)
print("sin(x) =",y)
# Valores de exp(x) para x [-1, 1]
x = np.linspace(-1, 1, 10)
y = np.exp(x)
print("\nexp(x)=",y)
# Valores de Ln(x) entre [1 - 10]
x = np.arange(1, 10, 0.1)
y = np.log(x + 10e-20)       # Para evitar la division entre 0!!!
print("\nln(x)=", y)

sin(x) = [ 2.44929360e-16  6.14212713e-01  9.69400266e-01  9.15773327e-01
  4.75947393e-01 -1.64594590e-01 -7.35723911e-01 -9.96584493e-01
 -8.37166478e-01 -3.24699469e-01  3.24699469e-01  8.37166478e-01
  9.96584493e-01  7.35723911e-01  1.64594590e-01 -4.75947393e-01
 -9.15773327e-01 -9.69400266e-01 -6.14212713e-01 -2.44929360e-16]

exp(x)= [0.36787944 0.45942582 0.57375342 0.71653131 0.89483932 1.11751907
 1.39561243 1.742909   2.17662993 2.71828183]

ln(x)= [0.         0.09531018 0.18232156 0.26236426 0.33647224 0.40546511
 0.47000363 0.53062825 0.58778666 0.64185389 0.69314718 0.74193734
 0.78845736 0.83290912 0.87546874 0.91629073 0.95551145 0.99325177
 1.02961942 1.06471074 1.09861229 1.13140211 1.16315081 1.19392247
 1.22377543 1.25276297 1.28093385 1.30833282 1.33500107 1.36097655
 1.38629436 1.41098697 1.43508453 1.45861502 1.48160454 1.5040774
 1.5260563  1.54756251 1.56861592 1.58923521 1.60943791 1.62924054
 1.64865863 1.66770682 1.68639895 1.70474809 1.7227666  1.74046617


Asi también hay ciertas operaciones que requieren especificar el "eje" que afectara la operacion. Por ejemplo el método *np.sum, np.prod, np.cumsum, np.cumprod*, etc. El eje 0 es el eje de las columnas y el eje 1 es el de las filas. Se muestra un ejemplo con *np.sum*:

In [30]:
vec = np.array([1, 2, 3, 4, 5])
print("vec =",vec)
print("sum(vec) =",np.sum(vec))
print()

mat = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
print("mat =\n", mat)
print("sum(mat) = ", np.sum(mat))
print("sum(mat, axis = 0) = ", np.sum(mat, axis=0))
print("sum(mat, axis = 1) = ", np.sum(mat, axis=1))


vec = [1 2 3 4 5]
sum(vec) = 15

mat =
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
sum(mat) =  45
sum(mat, axis = 0) =  [12 15 18]
sum(mat, axis = 1) =  [ 6 15 24]


## Algebra Lineal con numpy
Los arreglos de 2 dimensiones Matrices son especiales en ciencias e ingenieria para la solucion de ciertos problemas de algebra lineal. Es por eso que existe la clase especial matrix:

In [31]:
# Arreglos
A_array = np.array([[5, 2,  4],[1, 7, -3],[6, -10, 0]])
B_array = np.array([[11, 5,  -3],[0, 7, -3],[6, -10, 0]])

# Matrices
A_matrix = np.matrix(A_array)
B_matrix = np.matrix(B_array)

#Se imprimen los tipos
print("A_array ->", type(A_array))
print("A_matrix ->", type(A_matrix))

# Se imprimen los productos de A * B
# Seran diferentes ya que la operacion * sera elemento-a-elemento en arreglo y producto-punto en matrices
print("\nA_array * B_array =\n", A_array * B_array)
print("\nA_matrix * B_matrix =\n", A_matrix * B_matrix)

A_array -> <class 'numpy.ndarray'>
A_matrix -> <class 'numpy.matrix'>

A_array * B_array =
 [[ 55  10 -12]
 [  0  49   9]
 [ 36 100   0]]

A_matrix * B_matrix =
 [[ 79  -1 -21]
 [ -7  84 -24]
 [ 66 -40  12]]


En el caso de matrices hay algunos métodos (de la clase *"linalg"*) utiles:

In [32]:
# Otra forma de definir una matriz (estilo MATLAB)
A = np.matrix('1, 2, 3; 4, 5, 6; 7, 8, 9')
print("\nA =\n", A)
# La transpuesta es un atributo de una matriz
print("\nT(A) =\n", A.T)
# La inversa es un atributo de una matrix
print("\nInv(A) =\n", A.I)
# El determinante de una matriz es un método
print("\ndet(A) =\n", np.linalg.det(A))


A =
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

T(A) =
 [[1 4 7]
 [2 5 8]
 [3 6 9]]

Inv(A) =
 [[ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]
 [-6.30503948e+15  1.26100790e+16 -6.30503948e+15]
 [ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]]

det(A) =
 -9.51619735392994e-16


Esto nos puede servir para resolver sistemas de ecuaciones simultaneas, operacion muy recurrente en ingeneria, utilizando la operacion matricial X = inv(A) * B

In [33]:
# 4x - 2y + 6z = 8
# 2x + 8y + 2z = 4
# 6x + 10y + 3z = 0
A = np.matrix('4, -2, 6; 2, 8, 2; 6, 10, 3')
B = np.matrix('8; 4; 0')
X = A.I * B
print("x =", float(X[0]))
print("y =", float(X[1]))
print("z =", float(X[2]))

x = -1.8048780487804876
y = 0.2926829268292683
z = 2.6341463414634143


## EJEMPLOS DE APLICACION
### EJEMPLO 1
Un proyectil se dispara con una velocidad de 750 m/s. Calcule la altura h que alcanza el proyectil si el angulo de lanzamiento Theta cambia de 5° a 85° en incrementos de 5°.

In [34]:
import numpy as np
# Variables inciales
vel = 750; g = 9.81
# Se genera el vector de angulos de lanzamiento
ang = np.arange(0, 86, 5)
# Se calcula el tiempo de vuelo para cada angulo
hmax = vel**2 * np.sin(2*np.radians(ang)) / g
# Se muestran los resultados
for a, h in zip(ang, hmax):
    print("angulo = {:5.2f}°    alcance = {:8.2f}m".format(a, h))

angulo =  0.00°    alcance =     0.00m
angulo =  5.00°    alcance =  9956.89m
angulo = 10.00°    alcance = 19611.25m
angulo = 15.00°    alcance = 28669.72m
angulo = 20.00°    alcance = 36857.09m
angulo = 25.00°    alcance = 43924.57m
angulo = 30.00°    alcance = 49657.42m
angulo = 35.00°    alcance = 53881.46m
angulo = 40.00°    alcance = 56468.33m
angulo = 45.00°    alcance = 57339.45m
angulo = 50.00°    alcance = 56468.33m
angulo = 55.00°    alcance = 53881.46m
angulo = 60.00°    alcance = 49657.42m
angulo = 65.00°    alcance = 43924.57m
angulo = 70.00°    alcance = 36857.09m
angulo = 75.00°    alcance = 28669.72m
angulo = 80.00°    alcance = 19611.25m
angulo = 85.00°    alcance =  9956.89m


### EJEMPLO 2
Para calcular el coeficiente de rozamiento se mide la fuerza necesaria para mover una masa en reposo
segun la siguiente configuracion:

                   ------------
                  |            |
                  |      m     |------->>> F
                  |            |
    ==============================================

Se tienen los siguientes datos:
    
    Experimento      1     2     3      4      5     6
    Masa (kg)        2     4     5     10     20    50
    Fuerza (N)     12.5   23.5  30     61    118   294

Cual sera el valor de mu experimental?

In [35]:
import numpy as np

g = 9.81
m = np.array([2, 4, 5, 10, 20, 50])
F = np.array([12.5, 23.5, 30, 61, 118, 294])
mu = F / (m*g)
mu_media = np.mean(mu)
print("mu =", mu_media)

mu = 0.6117057424396874


### EJEMPLO 3
Una empresa fabrica botellas de jugos por galón con tres tipos de sabores combinados: naranja, piña y mango. Las combinaciones tienen  las siguientes combinaciones:

- 1 galon de mezcla uno: 3 cuartos de naranja, 0.75 cuartos de piña y 0.25 quartos de mango
- 1 galon de mezcla dos: 1 cuarto de naranja, 2.5 cuartos de piña y 0.5 quartos de mango
- 1 galon de mezcla tres: 0.5 cuartos de naranja, 0.5 cuartos de piña y 3 quartos de mango

¿Cuántos galones de cada mezcla pueden ser fabricados si 7,600 galones de jugo de naranja, 4,900 galones de piña y 3,500 galones de mango estan disponibles?

In [32]:
# Sistema de ecuaciones
# =====================
# x = galones de mezcla 1
# y = galones de mezcla 2
# z = galones de mezcla 3
#
# (3/4)x    + (1/4)y    + (0.5/4)z  = 7600
# (0.75/4)x + (2.5/4)y  + (0.5/4)z  = 4900
# (0.25/4)x + (0.5/4)y  + (3/4)z    = 3500

import numpy as np

A = np.matrix('3, 1, 0.5; 0.75, 2.5, 0.5; 0.25, 0.5, 3') / 4
B = np.matrix('7600; 4900; 3500');
X = A.I * B

print("Galones de mezcla 1: {:.1f}".format(float(X[0])))
print("Galones de mezcla 2: {:.1f}".format(float(X[1])))
print("Galones de mezcla 3: {:.1f}".format(float(X[2])))

Galones de mezcla 1: 8000.0
Galones de mezcla 2: 4800.0
Galones de mezcla 3: 3200.0


In [144]:
a=np.arange(3,100,2)
j=np.sqrt(a)
j=np.uint(j)+1


In [145]:
print(j)

[ 2  3  3  4  4  4  4  5  5  5  5  6  6  6  6  6  6  7  7  7  7  7  7  8
  8  8  8  8  8  8  8  9  9  9  9  9  9  9  9 10 10 10 10 10 10 10 10 10
 10]


In [143]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__dir__',
 '__doc__',
 '__file__',
 '__getattr__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_ad

In [110]:
#import math  
lista=[2,]  
for i in range(3,10, 2):  
    soy=True 
    print(int(np.sqrt(i)))
    for j in range(3,int(np.sqrt(i))+1,2):  
        if i%j==0:
            soy=False
    if soy:
        lista.append(i)  
print(lista)

1
2
2
3
[2, 3, 5, 7]
