In [1]:
# en python exixte la libreria Scipy para procesamiento cientifico,
# dentro de esta librería de esta librería existe el módulo para control de arreglos
#matemáticas


In [2]:
import numpy as np


In [13]:
#creabdo arreglos (arrays)

arr1= np.array([4,7,13,-1]) #a partir de un lista
print(arr1)
print(type(arr1))

#creando un arreglo a partir de un arange()
print()
arr2=np.arange(10)
print(arr2)

print()
arr3=np.arange(3,21,2)
print(arr3)

arr3=np.arange(3,21,0.2)
print(arr3)

#creando arreglos del método linispace()
print()
arr4=np.linspace(0,1,10)
print(arr4)

print()
arr5=np.linspace(5,20,15)
print(arr5)

#crando aleatorios:
print()
arr7=np.random.rand(10) #10 aleatorios entre [0,1>
print(arr7)
print()
arr8=np.random.randint(1,7,15) #15 aleatorios entre [1,7>
print(arr8)
print()
arr9= np.random.uniform(3,21,10) #10 aleatorios reales entre [3,21>
print(arr9)

[ 4  7 13 -1]
<class 'numpy.ndarray'>

[0 1 2 3 4 5 6 7 8 9]

[ 3  5  7  9 11 13 15 17 19]
[ 3.   3.2  3.4  3.6  3.8  4.   4.2  4.4  4.6  4.8  5.   5.2  5.4  5.6
  5.8  6.   6.2  6.4  6.6  6.8  7.   7.2  7.4  7.6  7.8  8.   8.2  8.4
  8.6  8.8  9.   9.2  9.4  9.6  9.8 10.  10.2 10.4 10.6 10.8 11.  11.2
 11.4 11.6 11.8 12.  12.2 12.4 12.6 12.8 13.  13.2 13.4 13.6 13.8 14.
 14.2 14.4 14.6 14.8 15.  15.2 15.4 15.6 15.8 16.  16.2 16.4 16.6 16.8
 17.  17.2 17.4 17.6 17.8 18.  18.2 18.4 18.6 18.8 19.  19.2 19.4 19.6
 19.8 20.  20.2 20.4 20.6 20.8]

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]

[ 5.          6.07142857  7.14285714  8.21428571  9.28571429 10.35714286
 11.42857143 12.5        13.57142857 14.64285714 15.71428571 16.78571429
 17.85714286 18.92857143 20.        ]

[0.42500839 0.72708715 0.16921694 0.81452621 0.57576228 0.11273542
 0.64595251 0.14068269 0.10101168 0.87366932]

[3 3 4 4 4 5 2 6 2 2 5 6 4 1 2]

[ 4.1

In [15]:
arr9= np.random.uniform(3,21,10)

larr9=list(arr9)
print(larr9)
print()
print(set(arr9))

[3.5014744361420136, 3.1051669331985727, 11.05727453867467, 8.480980055701288, 20.12662384227917, 4.9975546830047985, 7.894589101685242, 6.964125241549403, 16.587968233160062, 19.18242883167157]

{3.1051669331985727, 3.5014744361420136, 4.9975546830047985, 6.964125241549403, 7.894589101685242, 8.480980055701288, 11.05727453867467, 16.587968233160062, 19.18242883167157, 20.12662384227917}


In [23]:
# que se puede hacer los arreglos
arr1= np.array([4,7,13,-1])
print("Tamaño de arr1:",len(arr1))
print("cantidad de elementos de arr2:",arr1.size)
print()

#al igula que una lista los elementos de un arrreglo estan indexados:
arr2=np.arange(10)
print("Primer elemento de arr2: ",arr2[0])
print("Primer elemento de arr2: ",arr2[-1])
print("Primer elemento de arr2: ",arr2[2:6])
print()

#desde el punto de vista de modificacion, el arreglo es mutable:
arr3=np.arange(3,21,0.2)
arr3[0]=100 #modifica
print(arr3)
print()

#desde el punto de vista de insersion, el arreglo si es mutable:
arr4=np.arange(3,21,0.2)
#arr4=np.insert(arr2[2:4])


Tamaño de arr1: 4
cantidad de elementos de arr2: 4

Primer elemento de arr2:  0
Primer elemento de arr2:  9
Primer elemento de arr2:  [2 3 4 5]

[100.    3.2   3.4   3.6   3.8   4.    4.2   4.4   4.6   4.8   5.    5.2
   5.4   5.6   5.8   6.    6.2   6.4   6.6   6.8   7.    7.2   7.4   7.6
   7.8   8.    8.2   8.4   8.6   8.8   9.    9.2   9.4   9.6   9.8  10.
  10.2  10.4  10.6  10.8  11.   11.2  11.4  11.6  11.8  12.   12.2  12.4
  12.6  12.8  13.   13.2  13.4  13.6  13.8  14.   14.2  14.4  14.6  14.8
  15.   15.2  15.4  15.6  15.8  16.   16.2  16.4  16.6  16.8  17.   17.2
  17.4  17.6  17.8  18.   18.2  18.4  18.6  18.8  19.   19.2  19.4  19.6
  19.8  20.   20.2  20.4  20.6  20.8]



In [28]:
#aplicando operaciones matemáticas a arreglos:
ltemp=[45,67.8,100,90,50,36.7]
LF=[]
for v in ltemp:
    LF.append(v+9/5+32)
    
print(LF)
print()
LF=list(map(lambda x:x*9/5 +32,ltemp))
print(LF)

print()
atemp=np.array([45,67.8,100,90,50,36.7])
aF=atemp*9/5+32
print(aF)

for v in aF:
    print(v)

[78.8, 101.6, 133.8, 123.8, 83.8, 70.5]

[113.0, 154.04, 212.0, 194.0, 122.0, 98.06]

[113.   154.04 212.   194.   122.    98.06]
113.0
154.04
212.0
194.0
122.0
98.06


In [36]:
#Requerimiento 1
R=np.array([10,20,3.5,100,200])*1000

V=np.array([120,80,110,200,350])

I=V/R

P=V*I

print("R(Ohmios)\tV(voltios)\tI(amperios)\tP(watts)")
for r,v,i,p in zip(R,V,I,P):
    print("{:7.1f}k\t{:6}\t\t{:8.3f}\t{:6.2f}".format(r/1000,v,i,p))

R(Ohmios)	V(voltios)	I(amperios)	P(watts)
   10.0k	   120		   0.012	  1.44
   20.0k	    80		   0.004	  0.32
    3.5k	   110		   0.031	  3.46
  100.0k	   200		   0.002	  0.40
  200.0k	   350		   0.002	  0.61


In [42]:
#otras operaciones matemáticas aplicadas a arreglos

A=np.array([0.7,10,5.8,40,2.678,6.7])
#calculando seno de los elementos de A:
sA=np.sin(A)
print(sA)
print()
eA=np.exp(A)
print(A,end=('\n\n'))

#multiplica a cada elemento x5
mA=A*5
print(mA)
print()


print("Suma de todos los elementos de A: ",np.sum(A))
print("Promedio de todos los elementos de A: ",np.mean(A))
print("Máximo de todos los elementos de A: ",np.max(A))
print("Mínimo de todos los elementos de A: ",np.min(A))
print()
print(A)
print("Sumatoria acumulada de los elementos de A: ",np.cumsum(A))

[ 0.64421769 -0.54402111 -0.46460218  0.74511316  0.44716444  0.40484992]

[ 0.7   10.     5.8   40.     2.678  6.7  ]

[  3.5   50.    29.   200.    13.39  33.5 ]

Suma de todos los elementos de A:  65.878
Promedio de todos los elementos de A:  10.979666666666667
Máximo de todos los elementos de A:  40.0
Mínimo de todos los elementos de A:  0.7

[ 0.7   10.     5.8   40.     2.678  6.7  ]
Sumatoria acumulada de los elementos de A:  [ 0.7   10.7   16.5   56.5   59.178 65.878]


In [52]:

#Requerimiento 2:
i = np.arange(0.0,51.0) #arreglo de reales
# i = np.arange(0,51,dtype=float) 

aux=(-3)**(-i)/(2*i+1)

#aux = [r(0=1) r(i=1) .....r(i=50)]
api=np.sqrt(12)*np.cumsum(aux)

#api =[pi(n=0)  pi(n=1)   ... r(i=50)]

for ii,v in zip(i,api):
    print("Valor de pi para n={:2.0f}: {:.20f}".format(ii,v))


Valor de pi para n= 0: 3.46410161513775438635
Valor de pi para n= 1: 3.07920143567800375095
Valor de pi para n= 2: 3.15618147156995387803
Valor de pi para n= 3: 3.13785289159568048234
Valor de pi para n= 4: 3.14260474566308456446
Valor de pi para n= 5: 3.14130878546288316855
Valor de pi para n= 6: 3.14167431269883756784
Valor de pi para n= 7: 3.14156871594178399576
Valor de pi para n= 8: 3.14159977381150579134
Valor de pi para n= 9: 3.14159051093807972777
Valor de pi para n=10: 3.14159330450308127425
Valor de pi para n=11: 3.14159245428764632990
Valor de pi para n=12: 3.14159271502037995560
Valor de pi para n=13: 3.14159263454731396692
Valor de pi para n=14: 3.14159265952171384839
Valor de pi para n=15: 3.14159265173399759874
Valor de pi para n=16: 3.14159265417257538289
Valor de pi para n=17: 3.14159265340616489226
Valor de pi para n=18: 3.14159265364782624985
Valor de pi para n=19: 3.14159265357140338182
Valor de pi para n=20: 3.14159265359563510955
Valor de pi para n=21: 3.141592653

In [55]:
az=np.zeros(10)
a1=np.ones(10)
print(az)
print(a1)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [64]:
#indexamiento buleano
A=np.random.randint(1,100,24)
print(A)

ab=A%2==0
print(ab)
print()
pares=A[ab]
print(pares)
print()

#crea un arreglo con los multiplos de A
m7=A[A%7==0]
print(m7)
print()

#crea una arreglo con los elementos de A mayores a 6O
m60=A[A>60]
print(m60)

print()
#cra un arreglo con los elementos de A en el rango de [50,90]
mr=A[A>=50]
mr=mr[mr<=90]
print(mr)

[16 87 23 13 85 69 65 51  6 45 77 98 14 24 27 57 88 58 35 88  2 70 60  6]
[ True False False False False False False False  True False False  True
  True  True False False  True  True False  True  True  True  True  True]

[16  6 98 14 24 88 58 88  2 70 60  6]

[77 98 14 35 70]

[87 85 69 65 77 98 88 88 70]

[87 85 69 65 51 77 57 88 58 88 70 60]


In [88]:
nombres=np.array(["Juan","Maite","Laura","Richard","Carmen","Enrrique"])
notas=np.random.uniform(0,20,nombres.size)

#a=notas>np.mean(notas)
nom=nombres[notas>np.mean(notas)]

print("Notas generadas")
for nomb,nt in zip(nombres,notas):
    print("{:12}:{:8.2f} ".format(nomb,nt))
    
print('\nAlumnos cuyas notas estan por encima del promedio:',round(np.mean(notas),2))
for n in nom:
    print(n)

Notas generadas
Juan        :    8.08 
Maite       :   10.20 
Laura       :    8.64 
Richard     :    6.53 
Carmen      :    2.56 
Enrrique    :    9.17 

Alumnos cuyas notas estan por encima del promedio: 7.53
Juan
Maite
Laura
Enrrique
