In [4]:
#Python cuenta con la libreria SciPy para calculo científico. Dentro de esa librería esta 
#el módulo numpy que permite trabajar con arreglos matemáticos

In [2]:
import numpy as np

In [5]:
#creando arreglos (arrays)

#crear un arreglo en base a una lista:
arr1 = np.array([5,7,8,10,-1])
print(type(arr1))
print("\n",arr1)

#crear un arreglo en base al método arange():
arr2 = np.arange(10)  #Se crea un arreglo que empieza en 0, termina en 9, con saltos de 1 en 1
print("\n",arr2)
arr3 = np.arange(3,11,2) #Se crea un arreglo que empieza en 3, termina en 3, con saltos de 2 en 2
print("\n",arr3)
arr4 = np.arange(0,11,0.2) #Se crea un arreglo que empieza en 0, termina en 10, 
                           #con saltos de 0.2 en 0.2
print("\n",arr4)

#crear un arreglo en base al método linspace():
arr5 = np.linspace(0,1,10) #crea un arreglo que empieza en 0, termina en 1 y de tamaño 10
print("\n",arr5)
arr6 = np.linspace(3,20,20) #crea un arreglo que empieza en 3, termina en 20 y de tamaño 20
print("\n",arr6)

#crear un arreglo en base al módulo random de numpy:
arr7 = np.random.rand(10) #arreglo de tamaño 10 con valores aleatorios reales en el rango [0,1>
print("\n",arr7)
arr8 = np.random.randint(1,7,15) #arreglo de tamaño 15 con valores aleatorios enteros en el 
                                 #rango [1,7>
print("\n",arr8)
arr9 = np.random.uniform(5,11,10) #arreglo de tamaño 10 con valores aleatorios reales en el 
                                  #rango [5,11>
print("\n",arr9)

<class 'numpy.ndarray'>

 [ 5  7  8 10 -1]

 [0 1 2 3 4 5 6 7 8 9]

 [3 5 7 9]

 [ 0.   0.2  0.4  0.6  0.8  1.   1.2  1.4  1.6  1.8  2.   2.2  2.4  2.6
  2.8  3.   3.2  3.4  3.6  3.8  4.   4.2  4.4  4.6  4.8  5.   5.2  5.4
  5.6  5.8  6.   6.2  6.4  6.6  6.8  7.   7.2  7.4  7.6  7.8  8.   8.2
  8.4  8.6  8.8  9.   9.2  9.4  9.6  9.8 10.  10.2 10.4 10.6 10.8]

 [0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]

 [ 3.          3.89473684  4.78947368  5.68421053  6.57894737  7.47368421
  8.36842105  9.26315789 10.15789474 11.05263158 11.94736842 12.84210526
 13.73684211 14.63157895 15.52631579 16.42105263 17.31578947 18.21052632
 19.10526316 20.        ]

 [0.3429458  0.70356443 0.81263673 0.41732265 0.31751741 0.61758009
 0.4622023  0.80706958 0.47605016 0.70361756]

 [1 6 2 6 6 6 6 6 3 4 3 3 1 6 3]

 [ 9.2753271   7.72111822  6.09198829  8.67998157 10.362226    9.89607365
 10.25695185  7.39954457 10.60277942  9.79393555]


In [9]:
#Que podemos hacer con un arreglo:

arr1 = np.array([5,7,8,10,-1])
print("Tamaño del arreglo 1: ",len(arr1))
print("Cantidad de elementos del arreglo 1: ",arr1.size)

#los elementos de un arreglo al igual que en una lista estan indexados:
arr2 = np.arange(10)
print("\nAccede al primer elemento del arreglo 2: ",arr2[0])
print("Accede al ultimo elemento del arreglo 2: ",arr2[-1])
print("Accede a un tramo del arreglo 2: ",arr2[2:7])

#desde el punto de vista de modificación, el arreglo si es mutable
arr3 = np.arange(3,11,2) 
arr3[1]=100  #modifica el elemento de la posicion 1 por 100
print("\n",arr3)

#desde el punto de vista de insercion el arreglo es inmutable
arr4 = np.arange(0,11,0.2)
arr4 = np.insert(arr4,0,100) #tendría que actualizar
print("\n",arr4)

#desde el punto de vista de la eliminación el arreglo es inmutable
arr5 = np.linspace(0,1,10)
arr5 = np.delete(arr5,1) #tendría que actualizar
print("\n",arr5)

Tamaño del arreglo 1:  5
Cantidad de elementos del arreglo 1:  5

Accede al primer elemento del arreglo 2:  0
Accede al ultimo elemento del arreglo 2:  9
Accede a un tramo del arreglo 2:  [2 3 4 5 6]

 [  3 100   7   9]

 [100.    0.    0.2   0.4   0.6   0.8   1.    1.2   1.4   1.6   1.8   2.
   2.2   2.4   2.6   2.8   3.    3.2   3.4   3.6   3.8   4.    4.2   4.4
   4.6   4.8   5.    5.2   5.4   5.6   5.8   6.    6.2   6.4   6.6   6.8
   7.    7.2   7.4   7.6   7.8   8.    8.2   8.4   8.6   8.8   9.    9.2
   9.4   9.6   9.8  10.   10.2  10.4  10.6  10.8]

 [0.         0.22222222 0.33333333 0.44444444 0.55555556 0.66666667
 0.77777778 0.88888889 1.        ]


In [11]:
#operaciones matemáticas aplicadas a un arreglo:

ltemp = [56, 12.5, 19.5, 29, 100, 30]  #lista de grados centigrados

#usando for y append():
lF = []
for el in ltemp:
    lF.append(el*9/5+32)

print(lF)

#usando mapeo:
lF = list(map(lambda x:x*9/5+32,ltemp))
print("\n",lF)

#usando arreglos:
aTemp = np.array([56, 12.5, 19.5, 29, 100, 30])  #creando el arreglo de temperaturas
aF = aTemp*9/5+32  #creando el arreglo de grados F

print("\n",aF)

#un arreglo es iterable:
print()
for el in aF:
    print(el)

[132.8, 54.5, 67.1, 84.2, 212.0, 86.0]

 [132.8, 54.5, 67.1, 84.2, 212.0, 86.0]

 [132.8  54.5  67.1  84.2 212.   86. ]

132.8
54.5
67.1
84.2
212.0
86.0


In [53]:
#requerimiento 1:

R = np.array([10,20,3.5,100,200])*1000  #se crea el arreglo de resistencias

V = np.array([120,80,110,200,350])  #se crea el arreglo de voltajes

#creando al arreglo corrientes:
I = V/R

#creando al arreglo de potencias:
P = V*I

print("R(ohmios)\tV(voltios)\tI(amp.)\t\tP(watts)")
for r,v,i,p in zip(R,V,I,P):
    print("{:7}k\t{:6}\t\t{:5.2f}\t\t{:6.2f}".format(r/1000,v,i,p))

R(ohmios)	V(voltios)	I(amp.)		P(watts)
   10.0k	   120		 0.01		  1.44
   20.0k	    80		 0.00		  0.32
    3.5k	   110		 0.03		  3.46
  100.0k	   200		 0.00		  0.40
  200.0k	   350		 0.00		  0.61


In [13]:
#Aplicando otras operaciones matemáticas a un arreglo:

A = np.random.randint(1,11,10)
print(A)

#calcular el seno de cada valor de A
sA = np.sin(A)
print("\n",sA)

#calcuar la exponencial de cada valor de A
eA = np.exp(A)
print("\n",eA)

#elevar al cuadrado cada valor de A
cA = A**2
print("\n",cA)

#multiplicar cada valor de A por 5
a5 = A*5
print("\n",a5)

#sumar 3 a cada valor de A 
a3 = A+3
print("\n",a3)

print("\nLa suma de los elementos de A es: ",np.sum(A))
print("El promedio de los elementos de A es: ",np.mean(A))
print("El maximo valor de los elementos de A es: ",np.max(A))
print("El minimo valor de los elementos de A es: ",np.min(A))

az = np.zeros(10)  #arreglo de 10 ceros
print("\n",az)

au = np.ones(10)  #arreglo de 10 unos
print("\n",au)

#arreglo de 20 valores 10
a10 = np.ones(10)*10
print("\n",a10)

arr = np.array([1,2,3,4,5,6,7])
print("\n",arr)
print("La suma acumulada de arreglo es: ",np.cumsum(arr))

[ 8  7 10  8  8  5  8 10  4  4]

 [ 0.98935825  0.6569866  -0.54402111  0.98935825  0.98935825 -0.95892427
  0.98935825 -0.54402111 -0.7568025  -0.7568025 ]

 [ 2980.95798704  1096.63315843 22026.46579481  2980.95798704
  2980.95798704   148.4131591   2980.95798704 22026.46579481
    54.59815003    54.59815003]

 [ 64  49 100  64  64  25  64 100  16  16]

 [40 35 50 40 40 25 40 50 20 20]

 [11 10 13 11 11  8 11 13  7  7]

La suma de los elementos de A es:  72
El promedio de los elementos de A es:  7.2
El maximo valor de los elementos de A es:  10
El minimo valor de los elementos de A es:  4

 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]

 [10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]

 [1 2 3 4 5 6 7]
La suma acumulada de arreglo es:  [ 1  3  6 10 15 21 28]


In [6]:
#requerimiento 2:

i= np.arange(0,51,dtype=float)
au = (-3)**(-i)/(2*i+1)
cs = np.cumsum(au)*np.sqrt(12)

for k,r in enumerate(cs):
    print("Valor de pi para n={} :{:.15f}".format(k+1,r))

Valor de pi para n=1 :3.464101615137754
Valor de pi para n=2 :3.079201435678004
Valor de pi para n=3 :3.156181471569954
Valor de pi para n=4 :3.137852891595680
Valor de pi para n=5 :3.142604745663085
Valor de pi para n=6 :3.141308785462883
Valor de pi para n=7 :3.141674312698838
Valor de pi para n=8 :3.141568715941784
Valor de pi para n=9 :3.141599773811506
Valor de pi para n=10 :3.141590510938080
Valor de pi para n=11 :3.141593304503081
Valor de pi para n=12 :3.141592454287646
Valor de pi para n=13 :3.141592715020380
Valor de pi para n=14 :3.141592634547314
Valor de pi para n=15 :3.141592659521714
Valor de pi para n=16 :3.141592651733998
Valor de pi para n=17 :3.141592654172575
Valor de pi para n=18 :3.141592653406165
Valor de pi para n=19 :3.141592653647826
Valor de pi para n=20 :3.141592653571403
Valor de pi para n=21 :3.141592653595635
Valor de pi para n=22 :3.141592653587934
Valor de pi para n=23 :3.141592653590386
Valor de pi para n=24 :3.141592653589603
Valor de pi para n=25 :3.

In [16]:
#indexamiento booleano:

A = np.random.randint(1,100,24)
print(A)

ar = A%2==0  #ar es un arreglo booleano (solo contiene True o False)
print("\n",ar)
pares = A[ar]  #accederá a los elementos de A donde el indice del [] sea True
print(pares)

#simplificando:

#crea un arreglo con todos los pares de A:
pares = A[A%2==0]
print("\n",pares)

#crea un arreglo con todos los multiplos de 7 de A:
m7 = A[A%7==0]
print("\n",m7)

#crea un arrego con todos los valores de A mayores a 60
m60 = A[A>60]
print("\n",m60)

#almacena en un arreglo todos los valores 50 de A
m50 = A[A==50]
print("\n",m50)

#crea un arreglo con todos los valores de A que esten en el rango [50, 80]
arr = A[A>=50]
arr = arr[arr<=80]
print("\n",arr)

print("\n",any(A>50)) #hay algún elemento de A mayor a 50??
print("\n",all(A<200))  #todos los elementos de A son menores a 200?

[82  9 57 54 28 43 40  8 34 84 39 25 58 34 70 96 27 23 43 15 49 13 44 25]

 [ True False False  True  True False  True  True  True  True False False
  True  True  True  True False False False False False False  True False]
[82 54 28 40  8 34 84 58 34 70 96 44]

 [82 54 28 40  8 34 84 58 34 70 96 44]

 [28 84 70 49]

 [82 84 70 96]

 []

 [57 54 58 70]

 True

 True


In [112]:
#requeremiento 3:

#se crea el arreglo de nombres
nombres = np.array(["Juan","Maite","Laura","Richard","Carmen","Enrique"])

#creando el arreglo de notas:
notas = np.random.randint(0,21,6)

#mostrando la tabla:
for nomb,nota in zip(nombres,notas):
    print("{:8}:{:5}".format(nomb,nota))

#calculando el promedio:
prom = np.mean(notas)

nS = nombres[notas>prom]  #accede a los nombres cuyas notas pasaron el promedio
                          #y almacenalos en un arreglo

print("\nAlumnos cuyas notas estan por encima del promedio {:.2f}".format(prom))
for nomb in nS:
    print(nomb)

Juan    :   14
Maite   :    6
Laura   :   11
Richard :   15
Carmen  :   19
Enrique :   18

Alumnos cuyas notas estan por encima del promedio 13.83
Juan
Richard
Carmen
Enrique


In [ ]:
#revisar la carpeta blended donde encontrará la referencia sobre el manejo de arreglos
#bidimensionales.